name: run-testcases
on: [
  pull_request,
  workflow_dispatch,
]

jobs:
  test:
    name: run-testcases
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go_version: ['1.16', '1.17','1.18']
    # services:
    #   redis:
    #     image: redis:5.0-alpine
    #     ports: 
    #       - 6379:6379
    #   consul:
    #     image: consul:1.10
    #     ports:
    #       - 8500:8500
    #       - 8600:8600/udp
    #   etcd:
    #     image: quay.io/coreos/etcd:v3.5.0
    #     ports:
    #       - 2379:2379
    #       - 2380:2380
    #   zookeeper:
    #     image: zookeeper:3.7
    #     ports:
    #       - 8000:2181
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go_version }}
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: start services
        run: docker compose up -d
      - name: run testcases
        run: make test

